### ISSUE TITLE
adoptopenjdk is deprecated, using eclipse-temurin instead.

### ISSUE THREAD

**Issue by quotidian-ennui** [adaptris/docker-interlok-base#19]
https://hub.docker.com/_/adoptopenjdk is marked as deprected; and you should be using the eclipse-temurin 

- The dockerfile is virtually the same with `FROM eclipse-temurin:11-jdk` instead.
- Should it still be tagged the same thing since it no longer has the base image
- This has the knock-on effect of changing all your docker build scripts.
- You should port the docker builds to be a github action.

**Comment by sebastien-belin-adp** [comment]
It took some times but here we are:
- adopt openjdk has been replaced by eclipse temurin, only for v5 and java 17.
- The tag is temurin.
- We now use github actions to release docker images.
- docker-interlok-base will soon be not supported and everything will be done in docker-interlok for simplicity and because very little use of docker-interlok-base.
